/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking.system;
//import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.net.*;
import java.io.*;

/**
 *
 * @author Hp
 */
public class CreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccount
     */
        long id = Long.parseLong(String.valueOf(System.currentTimeMillis()).substring(1,10).concat(String.valueOf(0)));
          
        String accNum="100"+String.format("%06d",id);
        String idType=""; 
        String idNum="";
        String email="";
        String phone="";
        String date="";
        String fullName="";
        String picName="";
        String newPic="pictures";
        String pass="";
        DataInputStream di;
//        DataOutputStream dp;
        DataInputStream dis;
    public CreateAccount(DataInputStream dataI) throws IOException{

        try{
//            ServerSocket ss = new ServerSocket(8005);
//            
//            Socket s = ss.accept();
//        
//            
//            System.out.println("di opened");
           
            
            di = dataI;
//            dp = new DataOutputStream(s.getOutputStream());
            idType= di.readUTF();
            idNum= di.readUTF();
            email = di.readUTF();
            phone = di.readUTF();
            date = di.readUTF();
            fullName= di.readUTF();
            pass=di.readUTF();
            picName=di.readUTF();
        
            System.out.println("di closed");
            File fl = new File (picName);
            File f2 = new File (newPic);
            
            if(!f2.exists()) {
            	f2.mkdirs();
            }
//            DataInputStream dis = new DataInputStream(s.getInputStream());
            dis = dataI;
            FileOutputStream fout = new FileOutputStream(f2+"/"+fl.getName());
            newPic = newPic + "/" + fl.getName();
            
            int i;
            while ( (i = dis.read()) > -1) {
                fout.write(i);
            }

            fout.flush();
            
           
           
            System.out.println(idType+idNum+email+phone+date+fullName);
           
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
//        
        initComponents();
    }
    public String currentdateTime(){
        DateTimeFormatter dtf=DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        return  dtf.format(now);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        register_bodyPanel = new javax.swing.JPanel();
        register_headerPanel = new javax.swing.JPanel();
        registerFormLabel = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        idtypeField = new javax.swing.JTextField();
        idnumField = new javax.swing.JTextField();
        idNumLabel = new javax.swing.JLabel();
        accountLabel = new javax.swing.JLabel();
        accnumField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        dobField = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        passField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        register_bodyPanel.setBackground(new java.awt.Color(255, 204, 0));

        register_headerPanel.setBackground(new java.awt.Color(0, 51, 51));
        register_headerPanel.setForeground(new java.awt.Color(0, 51, 51));

        registerFormLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        registerFormLabel.setForeground(new java.awt.Color(255, 204, 0));
        registerFormLabel.setText("REGISTER FORM");

        javax.swing.GroupLayout register_headerPanelLayout = new javax.swing.GroupLayout(register_headerPanel);
        register_headerPanel.setLayout(register_headerPanelLayout);
        register_headerPanelLayout.setHorizontalGroup(
            register_headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(register_headerPanelLayout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(registerFormLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        register_headerPanelLayout.setVerticalGroup(
            register_headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, register_headerPanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(registerFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        backLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        backLabel.setForeground(new java.awt.Color(204, 51, 0));
        backLabel.setText("BACK");
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(0, 51, 51));
        idLabel.setText("ID type");

        idNumLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idNumLabel.setForeground(new java.awt.Color(0, 51, 51));
        idNumLabel.setText("Selected ID number");

        accountLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        accountLabel.setForeground(new java.awt.Color(0, 51, 51));
        accountLabel.setText("Account Number");

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(0, 51, 51));
        emailLabel.setText("Email  ID");

        phoneLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(0, 51, 51));
        phoneLabel.setText("Registered Phone");

        dateLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(0, 51, 51));
        dateLabel.setText("Date of Birth");

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(0, 51, 51));
        usernameLabel.setText("Username");

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 51, 51));
        passwordLabel.setText("Password");

        registerBtn.setBackground(new java.awt.Color(0, 102, 102));
        registerBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 204, 51));
        idtypeField.setText(idType);

        idnumField.setText(idNum);

        emailField.setText(email);

        accnumField.setText(accNum);

        phoneField.setText(phone);

        dobField.setText(date);

        userField.setText(fullName);

        passField.setText(pass);
        registerBtn.setText("REGISTER");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout register_bodyPanelLayout = new javax.swing.GroupLayout(register_bodyPanel);
        register_bodyPanel.setLayout(register_bodyPanelLayout);
        register_bodyPanelLayout.setHorizontalGroup(
            register_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(register_headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(register_bodyPanelLayout.createSequentialGroup()
                .addGroup(register_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(register_bodyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backLabel))
                    .addGroup(register_bodyPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(register_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(register_bodyPanelLayout.createSequentialGroup()
                                .addGroup(register_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailLabel)
                                    .addComponent(idNumLabel)
                                    .addComponent(accountLabel)
                                    .addComponent(phoneLabel)
                                    .addComponent(dateLabel)
                                    .addComponent(usernameLabel)
                                    .addComponent(passwordLabel))
                                .addGap(63, 63, 63)
                                .addGroup(register_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idnumField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(accnumField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(register_bodyPanelLayout.createSequentialGroup()
                                .addComponent(idLabel)
                                .addGap(145, 145, 145)
                                .addGroup(register_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(register_bodyPanelLayout.createSequentialGroup()
                                        .addGap(0, 272, Short.MAX_VALUE)
                                        .addComponent(registerBtn))
                                    .addGroup(register_bodyPanelLayout.createSequentialGroup()
                                        .addComponent(idtypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(71, 71, 71))
        );
        register_bodyPanelLayout.setVerticalGroup(
            register_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(register_bodyPanelLayout.createSequentialGroup()
                .addComponent(register_headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backLabel)
                .addGroup(register_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(register_bodyPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(register_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idtypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idLabel))
                        .addGap(18, 18, 18)
                        .addGroup(register_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idnumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idNumLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(register_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountLabel)
                            .addComponent(accnumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(register_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLabel)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(register_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneLabel))
                        .addGap(12, 12, 12)
                        .addGroup(register_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(register_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(register_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, register_bodyPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                        .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(register_bodyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(register_bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            System.out.println("driver loaded");

            Connection myconn= DriverManager.getConnection("jdbc:mysql://localhost:3306/banking_system","root","");
            System.out.println("database connected");

            String regsql = "insert into register values (?,?,?,?,?,?,?,?,?)";
            String transql ="insert into transaction (Account_num,Amount,Status,To_Or_From_Acc,Reason,Date) values(?,?,?,?,?,?)";
            String accsql="insert into account(accountnumber,accountbalance) values(?,?)";

            PreparedStatement ptstmt = myconn.prepareStatement(regsql);
            PreparedStatement transacstmt = myconn.prepareStatement(transql);
            PreparedStatement accstmt = myconn.prepareStatement(accsql);

            ptstmt.setString(1, idtypeField.getText());
            ptstmt.setString(2, idnumField.getText());
            ptstmt.setString(3, accnumField.getText());
            ptstmt.setString(4, emailField.getText());
            ptstmt.setString(5, phoneField.getText());
            ptstmt.setString(6, dobField.getText());
            ptstmt.setString(7, userField.getText());
            ptstmt.setString(8, passField.getText());
            ptstmt.setString(9, newPic);

            ptstmt.executeUpdate();

            transacstmt.setString(1, accnumField.getText());
            transacstmt.setInt(2, 50);
            transacstmt.setString(3, "Credit");
            transacstmt.setString(4, "Self");
            transacstmt.setString(5, "initial Deposit");
            transacstmt.setString(6,currentdateTime());

            transacstmt.executeUpdate();

            accstmt.setString(1, accnumField.getText());
            accstmt.setInt(2, 50);

            accstmt.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data has been inserted successfully");
        }catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:
        AdminDashboard obj = new AdminDashboard();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_backLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        try {
//			CreateAccount ca = new CreateAccount();
//			
//		} catch (IOException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
        
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//					new CreateAccount().setVisible(true);
//				} catch (IOException e) {
//					// TODO Auto-generated catch block
//					e.printStackTrace();
//				}
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accnumField;
    private javax.swing.JLabel accountLabel;
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dobField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idNumLabel;
    private javax.swing.JTextField idnumField;
    private javax.swing.JTextField idtypeField;
    private javax.swing.JTextField passField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel registerFormLabel;
    private javax.swing.JPanel register_bodyPanel;
    private javax.swing.JPanel register_headerPanel;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
