/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking.system;

import java.awt.Image;
import java.io.File;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author abete
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    String accountNum="";
    String profile="";
    public Dashboard(String acc,String pp) {
    	accountNum=acc;
    	profile=pp;
        initComponents();
    }
//    public Dashboard() {
//        initComponents();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        dashboardLabel = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        instantPaymentLabel = new javax.swing.JLabel();
        transactionLabel = new javax.swing.JLabel();
        transferToAccountLabel = new javax.swing.JLabel();
        billPaymentLabel = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        currentBalanceLabel = new javax.swing.JLabel();
        hideShowCheckBox = new javax.swing.JCheckBox();
        profileLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(156, 189, 238));

        jPanel1.setBackground(new java.awt.Color(70, 100, 168));
        jPanel1.setForeground(new java.awt.Color(70, 58, 109));

        dashboardLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dashboardLabel.setForeground(new java.awt.Color(236, 236, 236));
        dashboardLabel.setText("Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(dashboardLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(dashboardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        backLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        backLabel.setForeground(new java.awt.Color(204, 0, 51));
        backLabel.setText("BACK");
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });

        instantPaymentLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        instantPaymentLabel.setForeground(new java.awt.Color(0, 0, 102));
        instantPaymentLabel.setText("Instant Payment");
        instantPaymentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instantPaymentLabelMouseClicked(evt);
            }
        });

        transactionLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        transactionLabel.setForeground(new java.awt.Color(0, 0, 102));
        transactionLabel.setText("Transaction history");
        transactionLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionLabelMouseClicked(evt);
            }
        });

        transferToAccountLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        transferToAccountLabel.setForeground(new java.awt.Color(0, 0, 102));
        transferToAccountLabel.setText("Transfer To Account");
        transferToAccountLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferToAccountLabelMouseClicked(evt);
            }
        });

        billPaymentLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        billPaymentLabel.setForeground(new java.awt.Color(0, 0, 102));
        billPaymentLabel.setText("Bill payment");
        billPaymentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billPaymentLabelMouseClicked(evt);
            }
        });

        balanceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        balanceLabel.setText("Balance");

        currentBalanceLabel.setText("************");

        hideShowCheckBox.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        hideShowCheckBox.setText("Show/Hide");
        hideShowCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideShowCheckBoxActionPerformed(evt);
            }
        });
        
        
        File fl =  new File(profile);
        String picName= fl.getAbsolutePath();//picFile.getWidth()
        Image getAbsolutePath=null;
        ImageIcon icon = new ImageIcon(picName);
  
        Image image = icon.getImage();
        Image img =image.getScaledInstance(90,90,Image.SCALE_SMOOTH);
        
        
        profileLabel.setIcon(new ImageIcon(img)); // NOI18N
        profileLabel.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transferToAccountLabel)
                    .addComponent(billPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(transactionLabel)
                    .addComponent(instantPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(144, 144, 144))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(balanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(currentBalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hideShowCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(profileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 60, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferToAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instantPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transactionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentBalanceLabel)
                    .addComponent(hideShowCheckBox)
                    .addComponent(balanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    

    private void transferToAccountLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferToAccountLabelMouseClicked
        // TODO add your handling code here:
        TransferToAccount obj = new TransferToAccount(accountNum,profile);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_transferToAccountLabelMouseClicked

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:
        LoginForm obj = new LoginForm();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_backLabelMouseClicked

    private void billPaymentLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billPaymentLabelMouseClicked
        // TODO add your handling code here:
        billpayment obj = new billpayment(accountNum,profile);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_billPaymentLabelMouseClicked

    private void instantPaymentLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instantPaymentLabelMouseClicked
        // TODO add your handling code here:
        Instant_Payment obj = new Instant_Payment(accountNum,profile);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_instantPaymentLabelMouseClicked

    private void hideShowCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideShowCheckBoxActionPerformed
        // TODO add your handling code here:
        try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://192.168.43.86:3306/banking_system","client","cl@#12_nt");
            //to  get the data from th eaccount table of balance
            String sql="select accountbalance from account where accountnumber ="+accountNum+"";
            
            PreparedStatement ptst=conn.prepareStatement(sql);
            ResultSet rs= ptst.executeQuery(sql);
            
                if(rs.next()){
                    if(hideShowCheckBox.isSelected()){
                        currentBalanceLabel.setText(rs.getString("accountbalance")+" ETB");
                    }else{
                    currentBalanceLabel.setText("************");      
                    }
                }
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"error while establishing connection");
        }
        
    }//GEN-LAST:event_hideShowCheckBoxActionPerformed

    private void transactionLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionLabelMouseClicked
        // TODO add your handling code here:
        TransactionDetails obj = new TransactionDetails(accountNum,profile);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_transactionLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new dashboard().setVisible(true);
//            }
//        });
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Dashboard().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JLabel billPaymentLabel;
    private javax.swing.JLabel currentBalanceLabel;
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JCheckBox hideShowCheckBox;
    private javax.swing.JLabel instantPaymentLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JLabel transactionLabel;
    private javax.swing.JLabel transferToAccountLabel;
    // End of variables declaration//GEN-END:variables
}
