/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking.system;
import java.sql.*;
import javax.swing.*;
import java.time.*;
import java.time.format.DateTimeFormatter;


/**
 *
 * @author Hp
 */
public class TransferToAccount extends javax.swing.JFrame {

    /**
     * Creates new form TransferToAccount
     */
    String accountNum="";
    String profile = "";
    public TransferToAccount(String acc, String pp) {
    	accountNum=acc;
    	profile = pp;
        initComponents();
    }
    
    public String currentdateTime(){
    
    
    DateTimeFormatter dtf=DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
       return  dtf.format(now);
    }
//    public TransferToAccount() {
//        initComponents();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountPanel = new javax.swing.JPanel();
        transfer_bodyPanel = new javax.swing.JPanel();
        transfer_headerPanel = new javax.swing.JPanel();
        accountTransferLabel = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        yourAccountLabel = new javax.swing.JLabel();
        yourAccountField = new javax.swing.JTextField();
        amountField = new javax.swing.JTextField();
        recieverAccountField = new javax.swing.JTextField();
        amountLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        transfer_bodyPanel.setBackground(new java.awt.Color(156, 189, 238));

        transfer_headerPanel.setBackground(new java.awt.Color(70, 100, 168));

        accountTransferLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        accountTransferLabel.setForeground(new java.awt.Color(238, 238, 238));
        accountTransferLabel.setText("Transfer From Account");

        javax.swing.GroupLayout transfer_headerPanelLayout = new javax.swing.GroupLayout(transfer_headerPanel);
        transfer_headerPanel.setLayout(transfer_headerPanelLayout);
        transfer_headerPanelLayout.setHorizontalGroup(
            transfer_headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transfer_headerPanelLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(accountTransferLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transfer_headerPanelLayout.setVerticalGroup(
            transfer_headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transfer_headerPanelLayout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(accountTransferLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        backLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        backLabel.setForeground(new java.awt.Color(204, 51, 0));
        backLabel.setText("BACK");
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });
        yourAccountField.setText(accountNum);
        yourAccountLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        yourAccountLabel.setForeground(new java.awt.Color(0, 51, 102));
        yourAccountLabel.setText("Your Account number");

        amountLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        amountLabel.setForeground(new java.awt.Color(0, 51, 102));
        amountLabel.setText("Enter Amount");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Reciever Account number");

        submitBtn.setBackground(new java.awt.Color(0, 102, 204));
        submitBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transfer_bodyPanelLayout = new javax.swing.GroupLayout(transfer_bodyPanel);
        transfer_bodyPanel.setLayout(transfer_bodyPanelLayout);
        transfer_bodyPanelLayout.setHorizontalGroup(
            transfer_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transfer_headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(transfer_bodyPanelLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(transfer_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(transfer_bodyPanelLayout.createSequentialGroup()
                        .addGroup(transfer_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(transfer_bodyPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                .addGap(50, 50, 50)
                                .addComponent(recieverAccountField, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(transfer_bodyPanelLayout.createSequentialGroup()
                                .addComponent(yourAccountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yourAccountField, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(transfer_bodyPanelLayout.createSequentialGroup()
                                .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)
                                .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(transfer_bodyPanelLayout.createSequentialGroup()
                        .addComponent(submitBtn)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(transfer_bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transfer_bodyPanelLayout.setVerticalGroup(
            transfer_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transfer_bodyPanelLayout.createSequentialGroup()
                .addComponent(transfer_headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backLabel)
                .addGap(28, 28, 28)
                .addGroup(transfer_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yourAccountLabel)
                    .addComponent(yourAccountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(transfer_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLabel)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(transfer_bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recieverAccountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout accountPanelLayout = new javax.swing.GroupLayout(accountPanel);
        accountPanel.setLayout(accountPanelLayout);
        accountPanelLayout.setHorizontalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transfer_bodyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        accountPanelLayout.setVerticalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addComponent(transfer_bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String Amount = amountField.getText();
        String recieverAcc = recieverAccountField.getText();
        int AmountInt = Integer.parseInt(Amount);
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection Mconn= DriverManager.getConnection("jdbc:mysql://192.168.43.86:3306/banking_system","client","cl@#12_nt");
            //to get the data in jTestfield from mysql
//SENDER QUERY
            String sql1 = "select accountbalance from account where accountnumber ="+accountNum+"";
           
            PreparedStatement ptst = Mconn.prepareStatement(sql1);
           
            ResultSet rsl=ptst.executeQuery(sql1);
            if(rsl.next()){
            String accountblc =rsl.getString("accountbalance");
            int totalaccountblc= Integer.parseInt(accountblc) - AmountInt;
            String sql2="update `account` SET `accountbalance`='"+totalaccountblc+"' WHERE accountnumber = " + accountNum;
            PreparedStatement ptmt = Mconn.prepareStatement(sql2);
            if(Integer.parseInt(accountblc) < AmountInt){
                JOptionPane.showMessageDialog(null,"Account has Insufficient Amount!!!");
            }
            else{
            ptmt.execute();
            
//RECIEVER QUERY
            String sql3 = "select accountbalance from account where accountnumber ="+recieverAcc+"";
           
            PreparedStatement rtst = Mconn.prepareStatement(sql3);
           
            ResultSet rsl2=rtst.executeQuery(sql3);
            if(rsl2.next()){
            String Raccountblc =rsl2.getString("accountbalance");
            int Rtotalaccountblc= Integer.parseInt(Raccountblc) + AmountInt;
            String sql4="update `account` SET `accountbalance`='"+Rtotalaccountblc+"' WHERE accountnumber = " + recieverAcc;
            PreparedStatement ptmt2 = Mconn.prepareStatement(sql4);
            ptmt2.execute();
            
            String transql ="insert into transaction (Account_num,Amount,Status,To_Or_From_Acc,Reason,Date) values(?,?,?,?,?,?)";
            PreparedStatement transacstmt = Mconn.prepareStatement(transql);
            
                transacstmt.setString(1, accountNum);
                transacstmt.setInt(2, AmountInt);
                transacstmt.setString(3, "Debit");
                transacstmt.setString(4, recieverAcc);
                transacstmt.setString(5, "Transfer");
                transacstmt.setString(6, currentdateTime());
                
                transacstmt.executeUpdate();
            
            String transqlRc ="insert into transaction (Account_num,Amount,Status,To_Or_From_Acc,Reason,Date) values(?,?,?,?,?,?)";
            PreparedStatement transacstmtRc = Mconn.prepareStatement(transqlRc);
            
                transacstmtRc.setString(1, recieverAcc);
                transacstmtRc.setInt(2, AmountInt);
                transacstmtRc.setString(3, "Credit");
                transacstmtRc.setString(4, accountNum);
                transacstmtRc.setString(5, "Transfer");
                transacstmtRc.setString(6, currentdateTime());
                
                transacstmtRc.executeUpdate();
            
            
          JOptionPane.showMessageDialog(null,"your account has been debited with "+AmountInt + 
                  " for account number " + recieverAcc);
        }
            Mconn.close();
        }
            }
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:
        Dashboard obj = new Dashboard(accountNum,profile);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_backLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferToAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferToAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferToAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferToAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TransferToAccount().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountPanel;
    private javax.swing.JLabel accountTransferLabel;
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField recieverAccountField;
    private javax.swing.JButton submitBtn;
    private javax.swing.JPanel transfer_bodyPanel;
    private javax.swing.JPanel transfer_headerPanel;
    private javax.swing.JTextField yourAccountField;
    private javax.swing.JLabel yourAccountLabel;
    // End of variables declaration//GEN-END:variables
}
